SimplexNoise broke
I can't seem to get simplexnoise working. Error: "Shader error in
'EarthHeight': redefinition of 'mod289' at kernel CSMain at
Assets/Scripts/PlanetGeneration/Includes/SimplexNoise.cginc(22) (on
d3d11)"